### ISSUE TITLE
Add remaining heroes

### ISSUE THREAD

**Issue by NesaByte** [emreerkmen/dota_2_hero_app#1]
Hey there! I am inlove with DOTA2 and this app is really amazing, its really useful when it comes to learning about all the heroes!

I checked out your application and noticed that you only have Juggernaut's skills and stats in the app, I am hoping that you assign me to add the remaining heroes:

 - [x] Axe
 - [x] Bane 
 - [x] Bloodseeker
 - [x] FacelessVoid
 - [x] OgreMagi
 - [x] PhantomAssassin
 - [x] ShadowFiend
 - [x] Tusk
 - [x] Zeus

Thank you very much!

**Comment by emreerkmen** [comment]
Hi, It was great that someone noticed my app. I am so thankful. But I have bad news. As this is a learning project, I decided to stop develop this app .Sorry for that. Because there are a lot of info for a hero and I dont' know how can I desing a screen for such a huge info. Again I'm so gratefull for your attention.

**Comment by NesaByte** [comment]
Hey there! Please don't be sorry, I learned so much while adding new heroes information. The UI implementation is really good. And I really like this app.

You don't have to stop developing this app, you have 10 heroes right now. And its already pretty amazing.

You can then add these functionalities to the app:
- [ ] attach twitch links to pro player
- [ ] hero's skills can be clicked and it should show a description of how the skills work.

after this, I really think you have a very good application. :)

**Comment by NesaByte** [comment]
If you're not busy, I want to work with you on this application.

**Comment by emreerkmen** [comment]
Actually I'm busy right now and I want to spent my time to learn other topics of flutter such as MVVM architecture, BloC pattern, CI/CD pipeline etc. Unfortunately, continuing to develop this app doesn't help me to learn important topics that I mentioned before. So I decide to develop a new app that I can improve myself on those kind of things. Also I want publish my app to markets but probably I can not achieve this goal cause of DOTA 2 license problem. So I don't want o develop this app anymore. By the way I read your blog and I have saw that you write about my app. Thank you for that.

**Comment by NesaByte** [comment]
Thank you for your response, I understand now. It's true, Dota2 licensing will be a problem in the future. I am also learning Dart and want to improve that's why I am trying to work with other people. 

I am looking forward to your new application! Good luck!

Thank you for reading my blog :)
